name: Windows Unittests

on: [push, pull_request]

env:
  GST_REGISTRY: '~/registry.bin'
  KIVY_GL_BACKEND: 'angle_sdl2'
  KIVY_SPLIT_EXAMPLES: 1
  SETUPTOOLS_USE_DISTUTILS: local

jobs:
  unit_test:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [ '3.7', '3.8', '3.9', '3.10', '3.11', '3.12' ]
        arch: ['x64', 'x86']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }} on ${{ matrix.arch }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: Install dependencies
      run: |
        . .\.ci\windows_ci.ps1
        Install-kivy-test-run-win-deps
        Install-kivy-test-run-pip-deps
    - name: Install Kivy
      run: |
        . .\.ci\windows_ci.ps1
        Install-kivy
    - name: Test Kivy
      run: |
        . .\.ci\windows_ci.ps1
        Test-kivy
    - name: Test Kivy benchmarks
      if: matrix.python == '3.9' && matrix.arch == 'x64'
      run: |
        . .\.ci\windows_ci.ps1
        Test-kivy-benchmark
    - name: Upload benchmarks as artifact
      uses: actions/upload-artifact@v3
      with:
        name: benchmarks
        path: .benchmarks-kivy
