name: Windows Unittests

on: [push, pull_request]

env:
  GST_REGISTRY: '~/registry.bin'
  KIVY_GL_BACKEND: 'angle_sdl3'
  KIVY_SPLIT_EXAMPLES: 1
  SETUPTOOLS_USE_DISTUTILS: local

jobs:
  unit_test:
    runs-on: windows-2025
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        arch: ['x64']
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python }} on ${{ matrix.arch }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: Install Kivy
      run: |
        . .\.ci\windows_ci.ps1
        Install-kivy
    - name: Test Kivy
      run: |
        . .\.ci\windows_ci.ps1
        Test-kivy
    - name: Test Kivy benchmarks
      run: |
        . .\.ci\windows_ci.ps1
        Test-kivy-benchmark
    - name: Upload benchmarks as artifact
      uses: actions/upload-artifact@v5
      with:
        name: benchmarks-windows-unittests-python-${{ matrix.python }}-${{ matrix.arch }}
        path: .benchmarks-kivy
